cc_test(
    name = "callable",
    srcs = ["test_callable.cpp"],
    deps = ["@erasure"],
)

cc_test(
    name = "dereferenceable",
    srcs = ["test_dereferenceable.cpp"],
    deps = ["@erasure"],
)

cc_test(
    name = "meta",
    srcs = ["test_meta.cpp"],
    deps = ["@erasure"],
)

cc_test(
    name = "type_erasure_movable",
    srcs = ["test_type_erasure_movable.cpp"],
    deps = [
        "//:debug",
        "@erasure",
    ],
)
